# Generated by Django 6.0.7 on 2026-08-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.CharField(db_index=True, max_length=50)),
                ('service_type', models.CharField(choices=[('BUSINESS_PERMIT', 'Business Permit'), ('LAND_RATES', 'Land Rates'), ('BURSARY', 'Bursary'), ('HEALTH_CERT', 'Health Certificate')], db_index=True, max_length=30)),
                ('tracking_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('VERIFIED', 'Verified'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='SUBMITTED', max_length=30)),
                ('payload_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CountyNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.CharField(db_index=True, max_length=50)),
                ('service_type', models.CharField(choices=[('BUSINESS_PERMIT', 'Business Permit'), ('LAND_RATES', 'Land Rates'), ('BURSARY', 'Bursary'), ('HEALTH_CERT', 'Health Certificate')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('requirements', models.JSONField(default=list)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-scraped_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=30)),
                ('to_state', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
