# Generated by Django 6.0.7 on 2026-09-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service_Tracker', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='service_type',
            field=models.CharField(choices=[('BUSINESS_PERMIT', 'Business Permit'), ('LAND_RATES', 'Land Rates'), ('BURSARY', 'Bursary'), ('HEALTH_CERT', 'Health Certificate'), ('OTHER', 'Other')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='countynotice',
            name='service_type',
            field=models.CharField(choices=[('BUSINESS_PERMIT', 'Business Permit'), ('LAND_RATES', 'Land Rates'), ('BURSARY', 'Bursary'), ('HEALTH_CERT', 'Health Certificate'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
    ]
