# Generated by Django 6.0.7 on 2026-09-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='county_code',
            field=models.CharField(blank=True, default='', help_text='County code assigned to county officers.', max_length=50),
        ),
    ]
